-- SCRIPT PARA CREAR LA TABLA DE NOTIFICACIONES (RF20)
-- Este script permite el seguimiento de eventos automáticos para los usuarios.

USE PROYECTO_ARREGLOSAPP;

CREATE TABLE IF NOT EXISTS NOTIFICACIONES (
    notificacion_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    leida BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES USUARIOS(user_id) ON DELETE CASCADE
);

-- Verificar creación
DESCRIBE NOTIFICACIONES;
